#!/bin/bash

HOST=localhost:9098
TMPDIR=/tmp/idbsnapshot

influxd backup -database pm -host $HOST $TMPDIR
influxd restore -datadir /var/lib/influxdb/data -database pm $TMPDIR

sudo /bin/systemctl restart influxd.service

rm -r $TMPDIR/*
